# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false


target 'RxSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # Pods内のビルド警告を非表示
  inhibit_all_warnings!

  # Pods for RxSwiftSample
  pod 'Action'
  pod 'KRProgressHUD'
  pod 'Moya/RxSwift'

end

