# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false


target 'CombineSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # Pods内のビルド警告を非表示
  inhibit_all_warnings!

  # Pods for CombineSample
  pod 'KRProgressHUD'
  pod 'Moya/Combine'
  pod 'SwiftFormat/CLI'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
